In [1]:
import pandas as pd 
import numpy as np

In [2]:
l1 = [1,121,333,456]

In [3]:
type(l1)

list

In [4]:
ar = np.array(l1)

In [5]:
ar

array([  1, 121, 333, 456])

In [6]:
type(ar)

numpy.ndarray

In [7]:
l2 = [[1,2,3],[11,21,31],[111,222,333]]

In [8]:
np.array(l2)

array([[  1,   2,   3],
       [ 11,  21,  31],
       [111, 222, 333]])

In [9]:
np.arange(0 , 25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
num1 = np.linspace(1 , 5, 50) 
num1

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [15]:
1.08163265 - 1

0.08163264999999997

In [16]:
1.16326531 - 1.08163265

0.08163266000000013

In [17]:
np.eye(5)
# identity matrix ()
# diag is 1 rest every thing is zero square matrix 
# matrix with inverse u get identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.randint(1,20,3)

array([11,  2, 16])

In [19]:
np.random.randint(1,7,1)

array([4])

In [20]:
ar2 = np.array([2,4,6,23,56,11,490,60,90])

In [21]:
type(ar2)

numpy.ndarray

In [22]:
ar2.shape

(9,)

In [23]:
ar2.reshape(3,3)

array([[  2,   4,   6],
       [ 23,  56,  11],
       [490,  60,  90]])

In [24]:
ar2.max()

490

In [25]:
ar2.min()

2

In [26]:
ar2.argmax()

6

In [27]:
ar2.argmin()

0

In [28]:
ar3 = ar2

In [29]:
ar3 = ar3.reshape(3,3)

In [30]:
ar3.transpose()

array([[  2,  23, 490],
       [  4,  56,  60],
       [  6,  11,  90]])

In [31]:
l3 = ['a','b','a','c','C','a','d','A']

In [32]:
len(np.unique(l3))

6

In [33]:
np.sqrt(36)

6.0

In [34]:
np.square(7)

49

In [35]:
np.abs(-10)

10

In [36]:
np.add(4,5)

9

In [37]:
np.power(3,5)

243

In [38]:
np.power(9,.5)

3.0

In [39]:
np.log10(100)

2.0

In [40]:
np.log(2)

0.6931471805599453

In [41]:
np.log(2.718281828459045)

1.0

In [42]:
#     log of a base a == 1

In [43]:
np.log10(10)

1.0

# Math

In [44]:
import math 

In [45]:
math.exp(2)

7.38905609893065

In [46]:
math.factorial(5)

120

In [47]:
math.floor(67.998)

67

In [48]:
math.ceil(67.4598)

68

In [49]:
math.pi

3.141592653589793

In [50]:
math.gcd(27,9)

9

In [51]:
math.gcd(30,25)

5

In [52]:
math.pow(2,3)

8.0

In [53]:
np.lcm(10,15)

30

In [54]:
ran_num = np.random.normal(5,.2,100)
ran_num

array([4.77984193, 5.05706712, 5.43952629, 4.64591436, 5.15509323,
       5.01347819, 4.92252138, 5.24390174, 5.18356541, 4.87529755,
       5.17861286, 4.93744292, 4.61335446, 5.14503462, 5.41705486,
       5.25592794, 5.23473642, 4.96847192, 4.77549206, 4.65498892,
       4.87838801, 4.81206633, 4.94310134, 4.59620172, 4.98190349,
       5.13710578, 5.00981923, 5.12399979, 5.15833417, 5.01935118,
       4.90074178, 5.17402197, 5.07832869, 4.6928953 , 5.02219713,
       4.88616947, 5.20416958, 4.98613878, 5.27873837, 4.86293995,
       5.1957184 , 4.87182645, 5.27783639, 4.96106112, 4.82167612,
       5.26104583, 5.00715095, 4.7162744 , 5.27244808, 5.01931875,
       5.27808674, 4.8743405 , 5.06873391, 5.21002903, 4.78649456,
       4.87385001, 4.85434548, 4.81994098, 5.10459483, 5.18038446,
       4.54707256, 5.04966417, 4.69427766, 4.78656491, 5.01053191,
       4.87770367, 5.12616027, 4.96960191, 4.9837964 , 4.75873289,
       5.03478403, 5.01656104, 4.95137627, 5.14853895, 5.28143

In [55]:
ran_num.mean()

4.987397144165938

In [56]:
ran_num.std()

0.20655826587564868

In [57]:
## how to handle date and time

In [58]:
df = pd.DataFrame({"date": ('2021-06-03','2022-08-07')})

In [59]:
df

date
0  2021-06-03
1  2022-08-07

In [60]:
df1 = pd.DataFrame({"date": ('2021/06/03','2022/08/07')})

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   date    2 non-null      object
dtypes: object(1)
memory usage: 144.0+ bytes


In [62]:
df.date = df.date.astype('datetime64[ns]')

In [63]:
df.date.info()

<class 'pandas.core.series.Series'>
RangeIndex: 2 entries, 0 to 1
Series name: date
Non-Null Count  Dtype         
--------------  -----         
2 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 144.0 bytes


In [64]:
df1.date = pd.to_datetime(df1.date)

In [65]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   date    2 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 144.0 bytes


In [66]:
df1.date.dt.year

0    2021
1    2022
Name: date, dtype: int64

In [67]:
df1['year'] = df1.date.dt.year
df1['month'] = df1.date.dt.month
df1['Day_of_week'] = df1.date.dt.day_of_week
df1['week_day_name'] = df1.date.dt.week
df1['Day_of_year'] = df1.date.dt.dayofyear
df1['name_of_day'] = df1.date.dt.day_name()

C:\Users\shrey\AppData\Local\Temp\ipykernel_16264\170644177.py:4: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  df1['week_day_name'] = df1.date.dt.week


In [68]:
df1

date  year  month  Day_of_week  week_day_name  Day_of_year name_of_day
0 2021-06-03  2021      6            3             22          154    Thursday
1 2022-08-07  2022      8            6             31          219      Sunday

In [69]:
df_mixed = pd.DataFrame({'date': ("Apr 20, 2019","10-05-2020", '2021-12-20','20140404')})

In [70]:
df_mixed.date = pd.to_datetime(df_mixed.date)

In [71]:
df_mixed

date
0 2019-04-20
1 2020-10-05
2 2021-12-20
3 2014-04-04

In [72]:
df_invalid = pd.DataFrame({'date': ("Apr 20, 2019","6793", '2021-12-20','201404048')})

In [73]:
df_invalid.date = pd.to_datetime(df_invalid.date,errors = 'coerce')

In [74]:
df_invalid.date

0   2019-04-20
1          NaT
2   2021-12-20
3          NaT
Name: date, dtype: datetime64[ns]

In [75]:
dates =  ["02-03-2018"  , "06-07-2020",  "08-09-2005", "11-03-2017", "12-20-2021"]


In [76]:
# code which will extract year part of all Dates and store in a seperate list

In [77]:
df = pd.DataFrame({"dates": ("02-03-2018"  , "06-07-2020",  "08-09-2005", "11-03-2017", "12-20-2021")})

In [78]:
df.dates = pd.to_datetime(df.dates)

In [79]:
year_list =[]
for i in dates:
    year_list.append(i.split('-')[2])
year_list

['2018', '2020', '2005', '2017', '2021']

In [80]:
dict1 = {"Engg":10 ,"medical": 12,"mba":3,"manfu":44}

In [81]:
dict1.keys()

dict_keys(['Engg', 'medical', 'mba', 'manfu'])

In [82]:
dict1.values()

dict_values([10, 12, 3, 44])

In [83]:
dict2 = dict([(value, keys) for keys, value in dict1.items()])
for i in dict2:
    print(i, dict2[i])

10 Engg
12 medical
3 mba
44 manfu


In [84]:
## write a program (user defined pg ) which takes a number as input and check if that number is present betn 500  t0 1000

In [85]:
def find1(num):
    if num in range(500,1001):
        print("number in range")
    else:
        print("number not in  range")


In [86]:
num = int(input("enter a no"))
find1(num)

enter a no3
number not in  range


In [87]:
## write a program (user defined pg ) which takes a number as input and find the sum of all the numbers

# write a program (user define program) which take a number as i/p
# and find the sum of all number(natural number)


In [88]:
def sum(num):
        l1 = list(range(1,num+1))
        print(np.sum(l1))
    

In [89]:
sum(5)

15


# itertools

In [90]:
import itertools

In [91]:
# i have a two seperate nos (1,2)
# (1,1) (2,2), (1,2), (2,1)

In [92]:
print(list(itertools.product(["h","t"],repeat =2)))

[('h', 'h'), ('h', 't'), ('t', 'h'), ('t', 't')]


In [93]:
print(list(itertools.product(["h","t"],repeat =3)))

[('h', 'h', 'h'), ('h', 'h', 't'), ('h', 't', 'h'), ('h', 't', 't'), ('t', 'h', 'h'), ('t', 'h', 't'), ('t', 't', 'h'), ('t', 't', 't')]


In [94]:
# how many diff combination are possible when u thrw 2 dice

In [95]:
(list(itertools.product([1,2,3,4,5,6],repeat =2)))

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6)]

In [96]:
# what is probability of sum to be atleast 11 

In [97]:
l1 =list(itertools.product([1,2,3,4,5,6],repeat =2))
favou = 0
len(l1)
for i in l1:
    if(np.sum(i)) >=11:
        favou = favou +1 
    
    

In [98]:
print("total favourable outcomes are " ,favou)
print("prob is  " ,favou /len(l1))

total favourable outcomes are  3
prob is   0.08333333333333333


In [99]:
l2 =list(itertools.product(["H","T"],repeat =7))
len(l2)



128

In [100]:
favou1 = 0
len(l2)
for i in l2:
    if i.count("H") ==4:
        favou1 = favou1 +1
        
        

In [101]:
favou1

35

In [102]:
print(favou1/ len(l2))

0.2734375
